// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.20.3
// source: manga.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMangaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MangaId       string                 `protobuf:"bytes,1,opt,name=manga_id,json=mangaId,proto3" json:"manga_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMangaRequest) Reset() {
	*x = GetMangaRequest{}
	mi := &file_manga_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMangaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMangaRequest) ProtoMessage() {}

func (x *GetMangaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manga_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMangaRequest.ProtoReflect.Descriptor instead.
func (*GetMangaRequest) Descriptor() ([]byte, []int) {
	return file_manga_proto_rawDescGZIP(), []int{0}
}

func (x *GetMangaRequest) GetMangaId() string {
	if x != nil {
		return x.MangaId
	}
	return ""
}

type GetMangaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manga         *Manga                 `protobuf:"bytes,1,opt,name=manga,proto3" json:"manga,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMangaResponse) Reset() {
	*x = GetMangaResponse{}
	mi := &file_manga_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMangaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMangaResponse) ProtoMessage() {}

func (x *GetMangaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manga_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMangaResponse.ProtoReflect.Descriptor instead.
func (*GetMangaResponse) Descriptor() ([]byte, []int) {
	return file_manga_proto_rawDescGZIP(), []int{1}
}

func (x *GetMangaResponse) GetManga() *Manga {
	if x != nil {
		return x.Manga
	}
	return nil
}

type SearchMangaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchMangaRequest) Reset() {
	*x = SearchMangaRequest{}
	mi := &file_manga_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMangaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMangaRequest) ProtoMessage() {}

func (x *SearchMangaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manga_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMangaRequest.ProtoReflect.Descriptor instead.
func (*SearchMangaRequest) Descriptor() ([]byte, []int) {
	return file_manga_proto_rawDescGZIP(), []int{2}
}

func (x *SearchMangaRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchMangaRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchMangaRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SearchMangaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*Manga               `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchMangaResponse) Reset() {
	*x = SearchMangaResponse{}
	mi := &file_manga_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMangaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMangaResponse) ProtoMessage() {}

func (x *SearchMangaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manga_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMangaResponse.ProtoReflect.Descriptor instead.
func (*SearchMangaResponse) Descriptor() ([]byte, []int) {
	return file_manga_proto_rawDescGZIP(), []int{3}
}

func (x *SearchMangaResponse) GetResults() []*Manga {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchMangaResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MangaId       string                 `protobuf:"bytes,2,opt,name=manga_id,json=mangaId,proto3" json:"manga_id,omitempty"`
	Chapter       int64                  `protobuf:"varint,3,opt,name=chapter,proto3" json:"chapter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProgressRequest) Reset() {
	*x = UpdateProgressRequest{}
	mi := &file_manga_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProgressRequest) ProtoMessage() {}

func (x *UpdateProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manga_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProgressRequest.ProtoReflect.Descriptor instead.
func (*UpdateProgressRequest) Descriptor() ([]byte, []int) {
	return file_manga_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateProgressRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateProgressRequest) GetMangaId() string {
	if x != nil {
		return x.MangaId
	}
	return ""
}

func (x *UpdateProgressRequest) GetChapter() int64 {
	if x != nil {
		return x.Chapter
	}
	return 0
}

type UpdateProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProgressResponse) Reset() {
	*x = UpdateProgressResponse{}
	mi := &file_manga_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProgressResponse) ProtoMessage() {}

func (x *UpdateProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manga_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProgressResponse.ProtoReflect.Descriptor instead.
func (*UpdateProgressResponse) Descriptor() ([]byte, []int) {
	return file_manga_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateProgressResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Manga struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Artist        string                 `protobuf:"bytes,5,opt,name=artist,proto3" json:"artist,omitempty"`
	ChapterCount  int64                  `protobuf:"varint,6,opt,name=chapter_count,json=chapterCount,proto3" json:"chapter_count,omitempty"`
	PublishedYear int64                  `protobuf:"varint,7,opt,name=published_year,json=publishedYear,proto3" json:"published_year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manga) Reset() {
	*x = Manga{}
	mi := &file_manga_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manga) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manga) ProtoMessage() {}

func (x *Manga) ProtoReflect() protoreflect.Message {
	mi := &file_manga_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manga.ProtoReflect.Descriptor instead.
func (*Manga) Descriptor() ([]byte, []int) {
	return file_manga_proto_rawDescGZIP(), []int{6}
}

func (x *Manga) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Manga) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Manga) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Manga) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Manga) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *Manga) GetChapterCount() int64 {
	if x != nil {
		return x.ChapterCount
	}
	return 0
}

func (x *Manga) GetPublishedYear() int64 {
	if x != nil {
		return x.PublishedYear
	}
	return 0
}

var File_manga_proto protoreflect.FileDescriptor

const file_manga_proto_rawDesc = "" +
	"\n" +
	"\vmanga.proto\x12\bmanga.v1\",\n" +
	"\x0fGetMangaRequest\x12\x19\n" +
	"\bmanga_id\x18\x01 \x01(\tR\amangaId\"9\n" +
	"\x10GetMangaResponse\x12%\n" +
	"\x05manga\x18\x01 \x01(\v2\x0f.manga.v1.MangaR\x05manga\"_\n" +
	"\x12SearchMangaRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"V\n" +
	"\x13SearchMangaResponse\x12)\n" +
	"\aresults\x18\x01 \x03(\v2\x0f.manga.v1.MangaR\aresults\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"e\n" +
	"\x15UpdateProgressRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\bmanga_id\x18\x02 \x01(\tR\amangaId\x12\x18\n" +
	"\achapter\x18\x03 \x01(\x03R\achapter\"2\n" +
	"\x16UpdateProgressResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xcb\x01\n" +
	"\x05Manga\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06artist\x18\x05 \x01(\tR\x06artist\x12#\n" +
	"\rchapter_count\x18\x06 \x01(\x03R\fchapterCount\x12%\n" +
	"\x0epublished_year\x18\a \x01(\x03R\rpublishedYear2\xed\x01\n" +
	"\fMangaService\x12A\n" +
	"\bGetManga\x12\x19.manga.v1.GetMangaRequest\x1a\x1a.manga.v1.GetMangaResponse\x12E\n" +
	"\x06Search\x12\x1c.manga.v1.SearchMangaRequest\x1a\x1d.manga.v1.SearchMangaResponse\x12S\n" +
	"\x0eUpdateProgress\x12\x1f.manga.v1.UpdateProgressRequest\x1a .manga.v1.UpdateProgressResponseB\x1bZ\x19../internal/grpc/manga;pbb\x06proto3"

var (
	file_manga_proto_rawDescOnce sync.Once
	file_manga_proto_rawDescData []byte
)

func file_manga_proto_rawDescGZIP() []byte {
	file_manga_proto_rawDescOnce.Do(func() {
		file_manga_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_manga_proto_rawDesc), len(file_manga_proto_rawDesc)))
	})
	return file_manga_proto_rawDescData
}

var file_manga_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_manga_proto_goTypes = []any{
	(*GetMangaRequest)(nil),        // 0: manga.v1.GetMangaRequest
	(*GetMangaResponse)(nil),       // 1: manga.v1.GetMangaResponse
	(*SearchMangaRequest)(nil),     // 2: manga.v1.SearchMangaRequest
	(*SearchMangaResponse)(nil),    // 3: manga.v1.SearchMangaResponse
	(*UpdateProgressRequest)(nil),  // 4: manga.v1.UpdateProgressRequest
	(*UpdateProgressResponse)(nil), // 5: manga.v1.UpdateProgressResponse
	(*Manga)(nil),                  // 6: manga.v1.Manga
}
var file_manga_proto_depIdxs = []int32{
	6, // 0: manga.v1.GetMangaResponse.manga:type_name -> manga.v1.Manga
	6, // 1: manga.v1.SearchMangaResponse.results:type_name -> manga.v1.Manga
	0, // 2: manga.v1.MangaService.GetManga:input_type -> manga.v1.GetMangaRequest
	2, // 3: manga.v1.MangaService.Search:input_type -> manga.v1.SearchMangaRequest
	4, // 4: manga.v1.MangaService.UpdateProgress:input_type -> manga.v1.UpdateProgressRequest
	1, // 5: manga.v1.MangaService.GetManga:output_type -> manga.v1.GetMangaResponse
	3, // 6: manga.v1.MangaService.Search:output_type -> manga.v1.SearchMangaResponse
	5, // 7: manga.v1.MangaService.UpdateProgress:output_type -> manga.v1.UpdateProgressResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_manga_proto_init() }
func file_manga_proto_init() {
	if File_manga_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_manga_proto_rawDesc), len(file_manga_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_manga_proto_goTypes,
		DependencyIndexes: file_manga_proto_depIdxs,
		MessageInfos:      file_manga_proto_msgTypes,
	}.Build()
	File_manga_proto = out.File
	file_manga_proto_goTypes = nil
	file_manga_proto_depIdxs = nil
}
