// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function UpdateManga(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:Array<string>,arg7:number,arg8:number,arg9:number,arg10:number,arg11:number):Promise<void>;

export function UpdateMangaChapter(arg1:string,arg2:number):Promise<void>;
