// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentUsername() {
  return window['go']['services']['AuthService']['GetCurrentUsername']();
}

export function IsAdmin() {
  return window['go']['services']['AuthService']['IsAdmin']();
}

export function Login(arg1, arg2) {
  return window['go']['services']['AuthService']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['services']['AuthService']['Logout']();
}

export function Signup(arg1, arg2) {
  return window['go']['services']['AuthService']['Signup'](arg1, arg2);
}
