// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentUsername():Promise<string>;

export function IsAdmin():Promise<boolean>;

export function Login(arg1:string,arg2:string):Promise<void>;

export function Logout():Promise<void>;

export function Signup(arg1:string,arg2:string):Promise<void>;
