// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1, arg2) {
  return window['go']['services']['ChatService']['Connect'](arg1, arg2);
}

export function Disconnect() {
  return window['go']['services']['ChatService']['Disconnect']();
}

export function GetCurrentRoom() {
  return window['go']['services']['ChatService']['GetCurrentRoom']();
}

export function IsConnected() {
  return window['go']['services']['ChatService']['IsConnected']();
}

export function SendMessage(arg1) {
  return window['go']['services']['ChatService']['SendMessage'](arg1);
}

export function SetContext(arg1) {
  return window['go']['services']['ChatService']['SetContext'](arg1);
}

export function SwitchRoom(arg1) {
  return window['go']['services']['ChatService']['SwitchRoom'](arg1);
}
