// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function Connect(arg1:string,arg2:string):Promise<void>;

export function Disconnect():Promise<void>;

export function GetCurrentRoom():Promise<string>;

export function IsConnected():Promise<boolean>;

export function SendMessage(arg1:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SwitchRoom(arg1:string):Promise<void>;
