// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMangaByID(arg1) {
  return window['go']['services']['GRPCService']['GetMangaByID'](arg1);
}

export function SearchManga(arg1, arg2, arg3) {
  return window['go']['services']['GRPCService']['SearchManga'](arg1, arg2, arg3);
}

export function StartGRPCClient() {
  return window['go']['services']['GRPCService']['StartGRPCClient']();
}

export function UpdateProgress(arg1, arg2) {
  return window['go']['services']['GRPCService']['UpdateProgress'](arg1, arg2);
}
