// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1, arg2, arg3) {
  return window['go']['services']['LibraryService']['Add'](arg1, arg2, arg3);
}

export function List() {
  return window['go']['services']['LibraryService']['List']();
}
