// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function Add(arg1:string,arg2:string,arg3:any):Promise<void>;

export function List(arg1:string):Promise<models.ReadingLists>;

export function Remove(arg1:string):Promise<void>;

export function Update(arg1:string,arg2:string):Promise<void>;
