// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function Add(arg1:string,arg2:string,arg3:number):Promise<void>;

export function List():Promise<models.ReadingLists>;
