// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1, arg2, arg3) {
  return window['go']['services']['LibraryService']['Add'](arg1, arg2, arg3);
}

export function List(arg1) {
  return window['go']['services']['LibraryService']['List'](arg1);
}

export function Remove(arg1) {
  return window['go']['services']['LibraryService']['Remove'](arg1);
}

export function Update(arg1, arg2) {
  return window['go']['services']['LibraryService']['Update'](arg1, arg2);
}
