// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function ListMangaDetail(arg1:string):Promise<models.Manga>;

export function ListMangas(arg1:number,arg2:number,arg3:Array<string>):Promise<models.PaginatedMangasResponse>;

export function SearchMangas(arg1:string):Promise<Array<models.Manga>>;
