// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListAllMangas(arg1) {
  return window['go']['services']['MangaService']['ListAllMangas'](arg1);
}
