// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Start() {
  return window['go']['services']['NotifyService']['Start']();
}

export function Startup(arg1) {
  return window['go']['services']['NotifyService']['Startup'](arg1);
}

export function Subscribe(arg1) {
  return window['go']['services']['NotifyService']['Subscribe'](arg1);
}
