// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SetContext(arg1) {
  return window['go']['services']['SyncService']['SetContext'](arg1);
}

export function StartAutoConnect(arg1) {
  return window['go']['services']['SyncService']['StartAutoConnect'](arg1);
}

export function Stop() {
  return window['go']['services']['SyncService']['Stop']();
}
