// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function SetBaseURL(arg1:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function StartAutoConnect():Promise<void>;

export function Stop():Promise<void>;
