// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function GetMangaByID(arg1:string):Promise<Record<string, string>>;

export function SearchManga(arg1:string,arg2:number,arg3:number):Promise<services.SearchResult>;

export function StartGRPCClient():Promise<void>;

export function UpdateProgress(arg1:string,arg2:number):Promise<void>;
