// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {models} from '../models';

export function Add(arg1:string,arg2:string,arg3:any):Promise<void>;

export function GetProgressHistory(arg1:string):Promise<services.ProgressHistory>;

export function GetSyncStatus():Promise<Record<string, string>>;

export function List(arg1:string):Promise<models.ReadingLists>;

export function Remove(arg1:string):Promise<void>;

export function SyncProgress():Promise<void>;

export function Update(arg1:string,arg2:string):Promise<void>;

export function UpdateProgress(arg1:string,arg2:number,arg3:any,arg4:any,arg5:boolean):Promise<services.ProgressUpdateResponse>;
