// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListMangaDetail(arg1) {
  return window['go']['services']['MangaService']['ListMangaDetail'](arg1);
}

export function ListMangas(arg1, arg2, arg3, arg4) {
  return window['go']['services']['MangaService']['ListMangas'](arg1, arg2, arg3, arg4);
}

export function SearchMangas(arg1) {
  return window['go']['services']['MangaService']['SearchMangas'](arg1);
}
